# NumPy basics

## Import convention

In [1]:
import numpy as np
np.random.seed(657743)

In [2]:
%pylab inline
plt.style.use('ggplot')

Populating the interactive namespace from numpy and matplotlib


## Creating arrays from Python sequences

In [3]:
# Core data structure in numpy
?np.ndarray

Init signature: np.ndarray(self, /, *args, **kwargs)
Docstring:     
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
buffer : object exposing buffer int

In [4]:
np.ndarray((2,2), dtype=np.float)

array([[1., 1.],
       [1., 0.]])

It kinda works, but is not very convenient.

In [5]:
?np.array

Docstring:
array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.  This argument can only be used to 'upcast' the array.  For
    downcasting, use the .astype(t) method.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (

In [6]:
arr = np.array([[7, 2, 3], [3, 9, 6]])

In [7]:
arr

array([[7, 2, 3],
       [3, 9, 6]])

Each array has `shape`, `size`:

In [8]:
print("Array shape is", arr.shape)
print("Array size is", arr.size)
print("Array has %i dimensions" % arr.ndim)

Array shape is (2, 3)
Array size is 6
Array has 2 dimensions


And `dtype`, `itemsize` and `nbytes`:

In [9]:
print("Array dtype is", arr.dtype)
print("Each item in the array takes %i bytes" % arr.itemsize)
print("Array takes %i bytes" % arr.nbytes)

Array dtype is int32
Each item in the array takes 4 bytes
Array takes 24 bytes


## Creating arrays of special shape and/or type

In [10]:
zeros_array = np.zeros((2,6), dtype=bool)
zeros_array

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [11]:
arr

array([[7, 2, 3],
       [3, 9, 6]])

In [12]:
zeros_like_array = np.zeros_like(arr, dtype=np.complex128)
zeros_like_array

array([[0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j]])

In [13]:
ones_array = np.ones((3,9), dtype=np.float32)
ones_array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

In [14]:
ones_like_array = np.ones_like(zeros_array, dtype=np.float32)
ones_like_array

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [15]:
range_array = np.arange(10)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
range_array = np.arange(-5, 5)
range_array

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [17]:
range_array = np.arange(0, 5, 2)
range_array

array([0, 2, 4])

In [18]:
range_array = np.arange(0, 10, -2)

In [19]:
range_array

array([], dtype=int32)

In [20]:
range_array = np.arange(10, 0, -2)
range_array

array([10,  8,  6,  4,  2])

In [21]:
range_float_array = np.arange(-0.82, 5.32, 0.25)
range_float_array

array([-0.82, -0.57, -0.32, -0.07,  0.18,  0.43,  0.68,  0.93,  1.18,
        1.43,  1.68,  1.93,  2.18,  2.43,  2.68,  2.93,  3.18,  3.43,
        3.68,  3.93,  4.18,  4.43,  4.68,  4.93,  5.18])

## Basic indexing of numpy arrays

In [ ]:
range_float_array[1]

In [ ]:
range_float_array[1:2]

In [ ]:
range_float_array[:5]

In [ ]:
range_float_array[-5:-2]

In [ ]:
range_float_array

In [ ]:
arr

In [ ]:
arr[:1, 1:]

In [ ]:
arr[0, 1:]

In [ ]:
arr[0, ::2]

## Boolean and fancy indexing

In [ ]:
random_array = np.random.randn(10)
random_array

In [ ]:
random_array>0

In [ ]:
random_array[random_array>0]

In [ ]:
random_array[(random_array>0) | (random_array<-1)]

In [ ]:
random_array

In [ ]:
random_array[(random_array>0) & (random_array<1)]

In [ ]:
np.where(random_array>0)

In [ ]:
ix0, = np.where(random_array>0)

In [ ]:
ix0

In [ ]:
random_array[random_array>0]

In [ ]:
random_array[ix0]

In [ ]:
random_array = np.random.randn(3, 4)
random_array

In [ ]:
random_array[[0,2], [2, 3]]

## View vs. copy

In [25]:
arr

array([[7, 2, 3],
       [3, 9, 6]])

In [26]:
arr_view = arr[:, :]
arr_copy = arr.copy()

In [27]:
arr_view

array([[7, 2, 3],
       [3, 9, 6]])

In [28]:
arr_copy

array([[7, 2, 3],
       [3, 9, 6]])

In [29]:
arr_view[1:, 1:] = 41

In [30]:
arr_view

array([[ 7,  2,  3],
       [ 3, 41, 41]])

In [31]:
arr

array([[ 7,  2,  3],
       [ 3, 41, 41]])

In [32]:
arr_copy[1:, 1:] = 32

In [33]:
arr_copy

array([[ 7,  2,  3],
       [ 3, 32, 32]])

In [34]:
arr

array([[ 7,  2,  3],
       [ 3, 41, 41]])

## Changing array shape

In [35]:
arr

array([[ 7,  2,  3],
       [ 3, 41, 41]])

In [36]:
arr.reshape((1,6))

array([[ 7,  2,  3,  3, 41, 41]])

In [37]:
arr.reshape((6,-1))

array([[ 7],
       [ 2],
       [ 3],
       [ 3],
       [41],
       [41]])

In [38]:
arr.reshape((6,1,1))

array([[[ 7]],

       [[ 2]],

       [[ 3]],

       [[ 3]],

       [[41]],

       [[41]]])

In [39]:
np.expand_dims(arr, axis=1).shape

(2, 1, 3)

In [40]:
arr

array([[ 7,  2,  3],
       [ 3, 41, 41]])

In [41]:
arr.T

array([[ 7,  3],
       [ 2, 41],
       [ 3, 41]])

In [42]:
np.expand_dims(arr, axis=-1).shape

(2, 3, 1)

In [44]:
arr_t = np.transpose(np.expand_dims(arr, axis=-1), axes=(1,2,0))

In [45]:
 np.expand_dims(arr, axis=-1)

array([[[ 7],
        [ 2],
        [ 3]],

       [[ 3],
        [41],
        [41]]])

## Changing array type

In [ ]:
arr>2

In [ ]:
(arr>2).astype(np.int8)

In [ ]:
arr.astype(np.uint8)

In [ ]:
arr.astype(np.float32)

In [ ]:
arr.astype(np.complex128)

## Stacking arrays

In [ ]:
arr_1 = np.random.randint(10, size=(10,))
arr_2 = np.random.randint(10, size=(10,))

In [ ]:
arr_1, arr_2

In [ ]:
np.vstack([arr_1, arr_2])

In [ ]:
np.hstack([arr_1, arr_2])

In [ ]:
np.hstack([np.expand_dims(arr_1, 1), np.expand_dims(arr_2, 1)])

In [ ]:
arr_1.T

In [ ]:
np.vstack([arr_1, arr_2]).T

## Universal functions

For a full list of universal functions, see [ufunc reference](https://docs.scipy.org/doc/numpy-1.15.1/reference/ufuncs.html).

In [ ]:
arr_1

In [ ]:
arr_2

In [ ]:
arr

In [ ]:
arr.sum()

In [ ]:
arr.sum(axis=1)

In [ ]:
arr

In [ ]:
arr.sum(axis=1, keepdims=True)

In [ ]:
arr.mean(axis=0)

In [ ]:
arr_1, arr_2

In [ ]:
np.add(arr_1, arr_2, where=(arr_2<6))

In [ ]:
np.add(arr_1, arr_2, where=(arr_2<6), out=arr_2)

In [ ]:
arr_1

In [ ]:
arr_2